"use client"

import Link from "next/link"
import { ArrowLeft, Camera, KeyRound, Mail, Save, UserRound } from "lucide-react"
import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export default function ProfilePage() {
  const [saved, setSaved] = useState(false)
  return <main className="min-h-screen bg-background px-4 py-8 text-foreground sm:px-8"><div className="mx-auto max-w-3xl pb-24"><Link href="/" className="mb-8 inline-flex items-center gap-2 font-bold underline-offset-4 hover:underline"><ArrowLeft className="size-4" /> Volver al inicio</Link><header className="mb-8 border-b-4 border-current pb-6"><p className="mb-2 text-xs font-black uppercase tracking-[0.3em] text-muted-foreground">Postcraft / Cuenta</p><h1 className="text-4xl font-black tracking-tight sm:text-6xl">PERFIL</h1><p className="mt-3 text-muted-foreground">Administra tu identidad, datos de acceso y presencia en Postcraft.</p></header><form onSubmit={(event) => { event.preventDefault(); setSaved(true) }} className="space-y-6"><section className="rounded-2xl border-4 border-current bg-card p-5 shadow-[8px_8px_0px_0px_currentColor]"><div className="mb-6 flex items-center gap-3"><div className="grid size-16 place-items-center rounded-full border-4 border-current bg-muted"><UserRound className="size-8" /></div><Button type="button" variant="outline" className="rounded-xl border-2 border-current font-bold"><Camera className="mr-2 size-4" /> Cambiar foto</Button></div><div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="username">Nombre de usuario</Label><Input id="username" defaultValue="@yourbrand" className="border-2 border-current bg-background" /></div><div className="space-y-2"><Label htmlFor="name">Nombre visible</Label><Input id="name" defaultValue="Your Brand" className="border-2 border-current bg-background" /></div></div></section><section className="rounded-2xl border-4 border-current bg-card p-5"><div className="mb-5 flex items-center gap-3"><Mail className="size-6" /><h2 className="text-2xl font-black">Acceso y contacto</h2></div><div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="email">Correo electrónico</Label><Input id="email" type="email" defaultValue="hello@postcraft.app" className="border-2 border-current bg-background" /></div><div className="space-y-2"><Label htmlFor="password">Nueva contraseña</Label><Input id="password" type="password" placeholder="••••••••" className="border-2 border-current bg-background" /></div></div></section><div className="flex flex-wrap items-center gap-4"><Button type="submit" className="rounded-xl border-2 border-current font-black"><Save className="mr-2 size-4" /> Guardar cambios</Button>{saved && <span className="font-bold text-muted-foreground">Cambios guardados localmente.</span>}<Button asChild type="button" variant="outline" className="rounded-xl border-2 border-current font-bold"><Link href="/settings"><KeyRound className="mr-2 size-4" /> Configuraciones</Link></Button></div></form></div></main>
}
