"use client"

import { useState } from "react"
import { CalendarPlus, FileText, FolderOpen, ImagePlus, MoreHorizontal, Plus, Send, Video } from "lucide-react"

const tabs = ["All", "Drafts", "Scheduled", "Published"] as const
const content = [{ title: "Behind the scenes", type: "Reel", status: "Scheduled", date: "Today · 18:30", color: "bg-fuchsia-200" }, { title: "Launch notes", type: "Carousel", status: "Draft", date: "Edited 2h ago", color: "bg-cyan-200" }, { title: "Studio diary #03", type: "Video", status: "Published", date: "Yesterday", color: "bg-amber-200" }]

export default function ContentStudioDashboard() { const [active, setActive] = useState<(typeof tabs)[number]>("All"); const visible = active === "All" ? content : content.filter((item) => item.status === active.slice(0, -1) || (active === "Scheduled" && item.status === "Scheduled")); return <section id="studio" className="mb-10 rounded-2xl border-4 border-black bg-white p-5 shadow-[5px_5px_0px_0px_rgba(0,0,0,1)]"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-muted-foreground">Create, organize, publish</p><h2 className="text-2xl font-black">CONTENT STUDIO</h2></div><button type="button" className="inline-flex items-center gap-1 rounded-xl border-2 border-black bg-black px-3 py-2 text-sm font-black text-white"><Plus className="size-4" /> New piece</button></div><div className="mb-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{[[ImagePlus, "Visual"], [Video, "Video"], [FileText, "Copy"], [CalendarPlus, "Schedule"]].map(([Icon, label]) => <button key={label} type="button" className="flex items-center justify-center gap-2 rounded-xl border-2 border-black bg-lime-200 px-3 py-3 text-sm font-black hover:bg-lime-300"><Icon className="size-4" />{label}</button>)}</div><div className="mb-4 flex gap-2 overflow-x-auto pb-1">{tabs.map((tab) => <button key={tab} type="button" onClick={() => setActive(tab)} className={`rounded-full border-2 border-black px-3 py-1 text-xs font-black whitespace-nowrap ${active === tab ? "bg-black text-white" : "bg-white hover:bg-fuchsia-200"}`}>{tab}</button>)}</div><div className="space-y-3">{visible.map((item) => <div key={item.title} className={`flex items-center gap-3 rounded-xl border-2 border-black p-3 ${item.color}`}><div className="flex size-11 shrink-0 items-center justify-center rounded-lg border-2 border-black bg-white"><FolderOpen className="size-5" /></div><div className="min-w-0 flex-1"><p className="truncate font-black">{item.title}</p><p className="text-xs">{item.type} · {item.date}</p></div><span className="hidden rounded-full border-2 border-black bg-white px-2 py-1 text-[10px] font-black sm:inline">{item.status}</span><button type="button" aria-label={`More options for ${item.title}`}><MoreHorizontal className="size-5" /></button></div>)}{visible.length === 0 && <p className="rounded-xl border-2 border-dashed border-black p-5 text-center font-bold">Nothing here yet.</p>}</div><button type="button" className="mt-5 inline-flex items-center gap-2 rounded-xl border-2 border-black px-3 py-2 text-sm font-black hover:bg-lime-200"><Send className="size-4" /> Open publishing queue</button></section> }
