"use client"

import type React from "react"
import { useEffect, useRef, useState } from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Slider } from "@/components/ui/slider"
import { Download, ImageIcon, RotateCcw, Save, Upload } from "lucide-react"
import { downloadBlob, saveProject } from "@/lib/project-storage"

interface ImageStudioProps { onBack: () => void }
export default function ImageStudio({ onBack }: ImageStudioProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const [file, setFile] = useState<File | null>(null); const [image, setImage] = useState<HTMLImageElement | null>(null); const [filter, setFilter] = useState("none"); const [brightness, setBrightness] = useState(100); const [contrast, setContrast] = useState(100); const [rotation, setRotation] = useState(0)
  useEffect(() => { const canvas = canvasRef.current; if (!canvas || !image) return; const context = canvas.getContext("2d"); if (!context) return; const radians = rotation * Math.PI / 180; const width = image.width; const height = image.height; canvas.width = Math.abs(Math.cos(radians) * width) + Math.abs(Math.sin(radians) * height); canvas.height = Math.abs(Math.sin(radians) * width) + Math.abs(Math.cos(radians) * height); context.clearRect(0, 0, canvas.width, canvas.height); context.save(); context.translate(canvas.width / 2, canvas.height / 2); context.rotate(radians); context.filter = `${filter === "grayscale" ? "grayscale(1)" : filter === "sepia" ? "sepia(1)" : filter === "invert" ? "invert(1)" : ""} brightness(${brightness}%) contrast(${contrast}%)`; context.drawImage(image, -width / 2, -height / 2); context.restore() }, [image, filter, brightness, contrast, rotation])
  const load = (event: React.ChangeEvent<HTMLInputElement>) => { const nextFile = event.target.files?.[0]; if (!nextFile) return; setFile(nextFile); const nextImage = new Image(); nextImage.onload = () => setImage(nextImage); nextImage.src = URL.createObjectURL(nextFile) }
  const exportImage = () => { const canvas = canvasRef.current; if (canvas) canvas.toBlob((blob) => blob && downloadBlob(blob, "edited-image.png"), "image/png") }
  const save = async () => { if (file) await saveProject({ id: `image-${file.name}`, kind: "image", name: file.name, data: { filter, brightness, contrast, rotation }, updatedAt: Date.now() }) }
  return <Card className="rounded-xl border-4 border-black p-4 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] sm:p-6"><Button variant="outline" className="mb-4 rounded-xl border-2 border-black font-bold" onClick={onBack}>Back to Studios</Button><div className="grid gap-6 lg:grid-cols-[1fr_300px]"><main><h2 className="mb-4 text-2xl font-black">IMAGE STUDIO</h2>{image ? <div className="flex min-h-[360px] items-center justify-center rounded-xl border-4 border-black bg-[radial-gradient(#ddd_1px,transparent_1px)] [background-size:12px_12px]"><canvas ref={canvasRef} className="max-h-[520px] max-w-full" /></div> : <label className="flex aspect-video cursor-pointer flex-col items-center justify-center rounded-xl border-4 border-dashed border-black"><ImageIcon className="mb-4 size-14" /><span className="font-bold">Select an image</span><input type="file" accept="image/*" className="sr-only" onChange={load} /></label>}</main><aside className="rounded-xl border-4 border-black p-4"><h3 className="mb-4 text-xl font-bold">Image Controls</h3><label className="font-bold">Brightness: {brightness}%</label><Slider value={[brightness]} min={0} max={200} onValueChange={(v) => setBrightness(v[0])} className="my-4" /><label className="font-bold">Contrast: {contrast}%</label><Slider value={[contrast]} min={0} max={200} onValueChange={(v) => setContrast(v[0])} className="my-4" /><div className="grid grid-cols-2 gap-2"><Button variant={filter === "none" ? "default" : "outline"} onClick={() => setFilter("none")}>Normal</Button><Button variant={filter === "grayscale" ? "default" : "outline"} onClick={() => setFilter("grayscale")}>B&W</Button><Button variant={filter === "sepia" ? "default" : "outline"} onClick={() => setFilter("sepia")}>Sepia</Button><Button variant={filter === "invert" ? "default" : "outline"} onClick={() => setFilter("invert")}>Invert</Button></div><Button variant="outline" className="my-4 w-full rounded-xl border-2 border-black font-bold" onClick={() => setRotation((value) => value + 90)}><RotateCcw className="mr-2" />Rotate</Button><Button className="mb-3 w-full rounded-xl border-2 border-black bg-black font-bold text-white" onClick={save} disabled={!file}><Save className="mr-2" />Save Project</Button><Button variant="outline" className="w-full rounded-xl border-2 border-black font-bold" onClick={exportImage} disabled={!image}><Download className="mr-2" />Export PNG</Button></aside></div></Card>
}
