"use client"

import type React from "react"
import { useEffect, useRef, useState } from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Slider } from "@/components/ui/slider"
import { Download, Film, Pause, Play, Save, SkipBack, SkipForward, Upload } from "lucide-react"
import { downloadBlob, saveProject } from "@/lib/project-storage"

interface VideoStudioProps { onBack: () => void }
export default function VideoStudio({ onBack }: VideoStudioProps) {
  const videoRef = useRef<HTMLVideoElement>(null); const [file, setFile] = useState<File | null>(null); const [url, setUrl] = useState(""); const [playing, setPlaying] = useState(false); const [duration, setDuration] = useState(0); const [start, setStart] = useState(0); const [end, setEnd] = useState(0); const [speed, setSpeed] = useState(100); const [volume, setVolume] = useState(80)
  useEffect(() => () => { if (url) URL.revokeObjectURL(url) }, [url])
  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => { const nextFile = event.target.files?.[0]; if (!nextFile) return; if (url) URL.revokeObjectURL(url); setFile(nextFile); setUrl(URL.createObjectURL(nextFile)); setPlaying(false) }
  const toggle = () => { if (!videoRef.current) return; if (playing) videoRef.current.pause(); else void videoRef.current.play(); setPlaying(!playing) }
  const seek = (amount: number) => { if (videoRef.current) videoRef.current.currentTime = Math.max(0, Math.min(duration, videoRef.current.currentTime + amount)) }
  const save = async () => { if (file) await saveProject({ id: `video-${file.name}`, kind: "video", name: file.name, data: { start, end, speed, volume }, updatedAt: Date.now() }) }
  return <Card className="rounded-xl border-4 border-black p-4 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] sm:p-6"><Button variant="outline" className="mb-4 rounded-xl border-2 border-black font-bold" onClick={onBack}>Back to Studios</Button><div className="grid gap-6 lg:grid-cols-[1fr_300px]"><main><h2 className="mb-4 text-2xl font-black">VIDEO STUDIO</h2>{url ? <div className="overflow-hidden rounded-xl border-4 border-black bg-black"><video ref={videoRef} src={url} className="aspect-video w-full" onLoadedMetadata={(e) => { setDuration(e.currentTarget.duration); setEnd(e.currentTarget.duration) }} onEnded={() => setPlaying(false)} style={{ filter: "contrast(1.05)" }} /></div> : <label className="flex aspect-video cursor-pointer flex-col items-center justify-center rounded-xl border-4 border-dashed border-black"><Film className="mb-4 size-14" /><span className="font-bold">Select a video file</span><input type="file" accept="video/*" className="sr-only" onChange={handleFileChange} /></label>}{url && <><div className="mt-4 flex justify-center gap-2"><Button variant="outline" size="icon" className="rounded-xl border-2 border-black" onClick={() => seek(-5)}><SkipBack /></Button><Button size="icon" className="size-12 rounded-xl border-2 border-black bg-black text-white" onClick={toggle}>{playing ? <Pause /> : <Play />}</Button><Button variant="outline" size="icon" className="rounded-xl border-2 border-black" onClick={() => seek(5)}><SkipForward /></Button></div><div className="mt-4 rounded-xl border-2 border-black p-4"><div className="mb-2 flex justify-between font-bold"><span>Trim clip</span><span>{start.toFixed(1)}s – {end.toFixed(1)}s</span></div><Slider min={0} max={duration || 1} step={0.1} value={[start, end || duration]} onValueChange={(v) => { setStart(v[0]); setEnd(v[1] ?? end) }} /></div></>}</main><aside className="rounded-xl border-4 border-black p-4"><h3 className="mb-4 text-xl font-bold">Video Controls</h3><label className="font-bold">Speed: {speed}%</label><Slider value={[speed]} min={25} max={200} step={25} onValueChange={(v) => { setSpeed(v[0]); if (videoRef.current) videoRef.current.playbackRate = v[0] / 100 }} className="my-4" /><label className="font-bold">Volume: {volume}%</label><Slider value={[volume]} max={100} onValueChange={(v) => { setVolume(v[0]); if (videoRef.current) videoRef.current.volume = v[0] / 100 }} className="my-4" /><Button className="mb-3 w-full rounded-xl border-2 border-black bg-black font-bold text-white" onClick={save} disabled={!file}><Save className="mr-2" />Save Project</Button><Button variant="outline" className="w-full rounded-xl border-2 border-black font-bold" onClick={() => file && downloadBlob(file, `edited-${file.name}`)} disabled={!file}><Download className="mr-2" />Export Video</Button></aside></div></Card>
}
